// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWd3tk4Lv5ePLcfkkqAlypwLwpjcXxsSY',
    appId: '1:810504037552:web:a1e8f6d3bb315100100775',
    messagingSenderId: '810504037552',
    projectId: 'controledeabastecimento-6fedb',
    authDomain: 'controledeabastecimento-6fedb.firebaseapp.com',
    storageBucket: 'controledeabastecimento-6fedb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARF0bGGWK0tulWXmEsFvE3O7plIe0YCe4',
    appId: '1:810504037552:android:72d6e220260d9a9d100775',
    messagingSenderId: '810504037552',
    projectId: 'controledeabastecimento-6fedb',
    storageBucket: 'controledeabastecimento-6fedb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5Y9Cw2GE2_mQ0EBLTCmkGMLo4pCSTSYE',
    appId: '1:810504037552:ios:0082a53ce4fcf380100775',
    messagingSenderId: '810504037552',
    projectId: 'controledeabastecimento-6fedb',
    storageBucket: 'controledeabastecimento-6fedb.firebasestorage.app',
    iosBundleId: 'com.example.controleDeAbastecimento',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5Y9Cw2GE2_mQ0EBLTCmkGMLo4pCSTSYE',
    appId: '1:810504037552:ios:0082a53ce4fcf380100775',
    messagingSenderId: '810504037552',
    projectId: 'controledeabastecimento-6fedb',
    storageBucket: 'controledeabastecimento-6fedb.firebasestorage.app',
    iosBundleId: 'com.example.controleDeAbastecimento',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWd3tk4Lv5ePLcfkkqAlypwLwpjcXxsSY',
    appId: '1:810504037552:web:4711117c11c94ff9100775',
    messagingSenderId: '810504037552',
    projectId: 'controledeabastecimento-6fedb',
    authDomain: 'controledeabastecimento-6fedb.firebaseapp.com',
    storageBucket: 'controledeabastecimento-6fedb.firebasestorage.app',
  );
}
